spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hr?stringtype=unspecified
    username: postgres
    password: 123456

# MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.billyz.hrmanagement.entity,org.billyz.hrmanagement.vo
  configuration:
    map-underscore-to-camel-case: true

logging:
  file:
    name: logs/hr-app.log
  level:
    root: warn
    org.billyz.hrmanagement : info
    org.billyz.hrmanagement.aspect: debug